language: python
sudo: false
cache: pip

branches:
  only:
    - "/^[[:digit:]]{1,2}.[[:digit:]]$/"

python:
  - "3.6"

addons:
  postgresql: "9.5"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - python-simplejson
      - python-serial

env:
  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="cloud_platform_exoscale"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="cloud_platform_exoscale"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="cloud_platform_ovh"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="cloud_platform_ovh"
  - TESTS="1" ODOO_REPO="odoo/odoo" EXCLUDE="cloud_platform,cloud_platform_ovh,cloud_platform_exoscale"
  - TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE="cloud_platform,cloud_platform_ovh,cloud_platform_exoscale"
  global:
  - VERSION="13.0" LINT_CHECK="0" TESTS="0"

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_test_success
